### ISSUE TITLE
codec character issue

### ISSUE THREAD

**Issue by KianBrose** [KianBrose/Xav#9]
Traceback (most recent call last):
  File "/home/prod/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "Xav.py", line 25, in on_ready
    print(f"Logged as {bot.user}")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 11-12: ordinal not in range(256)

**Comment by GamrayW** [comment]
That's because of the name of the bot
I have no idea how to fix it except change the name or just don't print it
